server:
  port: ${SERVICE_PORT:8080}
  servlet:
    context-path: /users

jwt:
  secret: ${SECRET_KEY_JWT:vYntQrwoNcnyu8R7R92CI7YrcDHpAnLO}
  expiration: ${EXPIRATION_TIME_JWT:3600000}  # 1 hora en ms

spring:
  application:
    name: api-users
  datasource:
    url: ${DB_URL:jdbc:h2:mem:mydb}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:password}
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  validation:
    email-regex: ${EMAIL_REGEX:^[a-z]+@[a-z]+\.[a-z]{2,}$}
    password-regex: ${PASSWORD_REGEX:[a-zA-Z0-9]{6,10}}

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO